global:
  scrape_interval: 1m
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['cargoship.cawa:9100']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'fw.cawa'
    static_configs:
      - targets: ['fw.cawa:9100']
  - job_name: 'pihole.cawa'
    static_configs:
      - targets: ['10.10.10.12:9100']
  - job_name: 'bellatrix.cawa'
    static_configs:
      - targets: ['bellatrix.cawa:9100']
  - job_name: 'alnitak.cawa'
    static_configs:
      - targets: ['alnitak.cawa:9100']
  - job_name: 'alnilam.cawa'
    static_configs:
      - targets: ['alnilam.cawa:9100']
  - job_name: 'cadvisor.cawa'
    static_configs:
      - targets: ['cadvisor.cawa:8081']
